
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-1
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBmDgZA","is_bot":false,"login":"Frank404NotFound","name":"Frank Zhong"},"headRefName":"Frank-JokeService-Controller","number":20,"title":"Frank joke service controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/20"},{"author":{"id":"U_kgDOBmDgZA","is_bot":false,"login":"Frank404NotFound","name":"Frank Zhong"},"headRefName":"Frank-JokeService","number":19,"title":"Frank joke service","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/19"},{"author":{"id":"MDQ6VXNlcjkwOTg2OTAy","is_bot":false,"login":"miguel-luis9","name":""},"headRefName":"Luis-Location","number":18,"title":"Luis - Add Location Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/18"}]
