
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-1
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBX3XhQ","is_bot":false,"login":"phamaiden","name":""},"headRefName":"Aiden-HomeController","number":27,"title":"Aiden - Updated home controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/27"},{"author":{"id":"U_kgDOB7yP8g","is_bot":false,"login":"RuizheJiang","name":""},"headRefName":"Ruizhe-Zipcode-Controller","number":25,"title":"rj - add zipcode controller and test","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/25"}]
