
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-1
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBqpQ0A","is_bot":false,"login":"monicatrinh1","name":"Monica Trinh"},"headRefName":"Monica-TidesQuery","number":36,"title":"Add TidesQuery Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/36"},{"author":{"id":"U_kgDOBmDgZA","is_bot":false,"login":"Frank404NotFound","name":"Frank Zhong"},"headRefName":"Frank-JokeService-Controller","number":35,"title":"Frank joke service controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/35"},{"author":{"id":"U_kgDOBXjsvQ","is_bot":false,"login":"ericknee","name":""},"headRefName":"Eric-University-Controller","number":34,"title":"Add University Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/34"},{"author":{"id":"U_kgDOB7yP8g","is_bot":false,"login":"RuizheJiang","name":""},"headRefName":"Ruizhe-Zipcode-Controller","number":31,"title":"fixed bug for zipcode controller & test","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/31"}]
