
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-1
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBX3XhQ","is_bot":false,"login":"phamaiden","name":""},"headRefName":"Aiden-PublicHoliday","number":23,"title":"Add Public Holiday Service ","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/23"},{"author":{"id":"U_kgDOBXjsvQ","is_bot":false,"login":"ericknee","name":""},"headRefName":"Eric-University","number":22,"title":"Add University Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/22"},{"author":{"id":"U_kgDOB7yP8g","is_bot":false,"login":"RuizheJiang","name":""},"headRefName":"Ruizhe-ZipcodeService","number":21,"title":"Ruizhe zipcode service","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-1/pull/21"}]
